In [2]:
import numpy as np

In [18]:
length = 10.0 # in meter

x_grids = 1
y_grids = 1

no_of_cv_in_grid_layout = (5, 5)
x_cv, y_cv = no_of_cv_in_grid_layout

if x_cv != 0 and y_cv != 0:
    x_grids = x_cv * 2 + 3
    y_grids = y_cv * 2 + 3

elif x_cv == 0:
    x_grids = y_cv * 2 + 3
    
else:
    y_grids = x_cv * 2 + 3

matrix = np.zeros((x_grids, y_grids))

l = len(matrix[0]) # length of the grid array
delta_x = length / l
delta_y = delta_x
if y_cv

print(l)

13


In [ ]:
# given B.Cs.
inlet_u = ('given', 76.0)
outlet_u = ('not_given', 11.0)

inlet_v = ('not_given', 0.0)

outlet_v = ('not_given', 0.0)
inlet_p = ('given', 11.0)
outlet_p = ('not_given', 2.0)

# implementing B.Cs. on grid layout
# pressure
matrix[0::2, 0] = inlet_p[1] # at inlet
matrix[0::2, l-1] = outlet_p[1] # at outlet
# u velocity
matrix[0::2, 1] = inlet_u[1] # inlet
matrix[0::2, l-2] = outlet_u[1] # outlet
# v velocity
matrix[1::2, 0] = inlet_v[1] # inlet
matrix[1::2, l-1] = outlet_v[1] # outlet

print(matrix)

[[ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 11.  76.   0.   0.   0.   0.   0.   0.   0.   0.   0.  11.   2.]]


In [65]:
# u velocity coefficients
Fe = np.zeros((7,6))
Fw = np.zeros((7,6))
Fn = np.zeros((7,6))
Fs = np.zeros((7,6))
De = np.zeros((7,6))
Dw = np.zeros((7,6))
Dn = np.zeros((7,6))
Ds = np.zeros((7,6))
aP_o = np.zeros((7,6))
delta_p = np.zeros((7,6))

zero = np.zeros((7,6))

row = 2.0
mu = 1.0
g = 9.8
delta_x = 1.0
delta_y = 1.0
delta_t = 1.0
A = delta_x * delta_y

Fw[:,1:] = row / 2.0 * (matrix[0::2, 3::2] + matrix[0::2, 1:11:2])
Fe[:,0:5] = row / 2.0 * (matrix[0::2, 1:11:2] + matrix[0::2, 3::2])
Fn[1:,:] = row / 2.0 * (matrix[2::2, 1::2] + matrix[0:12:2, 1::2])
Fs[0:6,:] = row / 2.0 * (matrix[0:12:2,1::2] + matrix[2::2, 1::2])

De[:,0:5] = mu / delta_x
Dw[:,1:] = mu / delta_x
Dn[1:,:] = mu / delta_y
Ds[0:6,:] = mu / delta_y

delta_p = (matrix[0::2, 0:12:2] - matrix[0::2, 2::2]) / delta_x
b = delta_p + row * g 

aE = (De + np.fmax(-Fe, zero)) / delta_x
aW = (Dw + np.fmax(Fw, zero)) / delta_x
aN = (Dn + np.fmax(-Fn, zero)) / delta_y
aS = (Ds + np.fmax(Fs, zero)) / delta_y
aP_o[:,:] = row / delta_t

aP = aP_o + np.fmax(Fe, zero) / delta_x + np.fmax(-Fw, zero) / delta_x + np.fmax(Fn, zero) / delta_y + np.fmax(-Fs, zero) / delta_y + De / delta_x + Dw / delta_x + Dn / delta_y + Ds / delta_y    

#ap = row * A / delta_t + 
#aw[1] = -11.0
#for i in np.nditer(aw):
    #max(i,0.0)
print(aE,'\n')
print(aW,'\n')
print(aN,'\n')
print(aS,'\n')
print(aP,'\n')
print(b)

[[ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.]] 

[[  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]
 [  0.  12.  12.  12.  12.  12.]] 

[[ 0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]] 

[[ 12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.]
 [ 12.  12.  12.  12.  12.  12.]
 [  0.   0.   0.   0.   0.   0.]] 

[[ 15.  16.  16.  16.  16.   4.]
 [ 27.  28.  28.  28.  28.  16.]
 [ 27.  28.  28.  28.  28.  16.]
 [ 27.  28.  28.  28.  28.  16.]
 [ 27.  28.  28.

In [89]:
no_of_rows, no_of_colums = aP.shape
# B.Cs.
inlet_u = (75.0, 'given')
inlet_p = (118.0, 'given')
outlet_u = (0.0, 'given')
outlet_p = (0.0, 'given')
# from B.Cs.
if 
u_values = matrix[0::2, 1::2]
source = np.zeros(no_of_rows)

for col in range(0, no_of_colums):
    #col = 5
    tdma = np.diag(aP[:, col], k=0) + np.diag(-aN[1:, col], k=1) + np.diag(-aS[0:6, col], k=-1)
    if col == 0:
        source[:] = b[:, col] + u_values[:, col+1]
    elif col == 5:
        source[:] = b[:, col] + u_values[:, col-1]
    else:
        source[:] =  b[:, col] + u_values[:, col+1] + u_values[:, col-1]

    #from boundary conditions


    u_solution = np.linalg.solve(tdma, source)
    u_values[:, col] = u_solution[:]

print(u_values, '\n')
print(u_solution)
#print(tdma, ' = ', source)

[[ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]
 [ 1.50779623  1.50779623  1.50937789  1.53304379  1.88634245  7.16211415]] 

[ 7.16211415  7.16211415  7.16211415  7.16211415  7.16211415  7.16211415
  7.16211415]


In [90]:
print(matrix)

[[ 1.          1.50779623  1.          1.50779623  1.          1.50937789
   1.          1.53304379  1.          1.88634245  1.          7.16211415
   1.        ]
 [ 3.3         0.          3.3         0.          3.3         0.          3.3
   0.          3.3         0.          3.3         0.          3.3       ]
 [ 1.          1.50779623  1.          1.50779623  1.          1.50937789
   1.          1.53304379  1.          1.88634245  1.          7.16211415
   1.        ]
 [ 3.3         0.          3.3         0.          3.3         0.          3.3
   0.          3.3         0.          3.3         0.          3.3       ]
 [ 1.          1.50779623  1.          1.50779623  1.          1.50937789
   1.          1.53304379  1.          1.88634245  1.          7.16211415
   1.        ]
 [ 3.3         0.          3.3         0.          3.3         0.          3.3
   0.          3.3         0.          3.3         0.          3.3       ]
 [ 1.          1.50779623  1.          1.50779623

In [11]:
mat = np.zeros((1,3))
print(mat)

[[ 0.  0.  0.]]
